### PR TITLE
Issue live debugging

### PR DESCRIPTION
**Pull request by stvoutsin**
Investigating the recent downtime (slowness) of the cluster with Prometheus

### CODE REVIEW

**Comment by stvoutsin** [comment]
Note that the live deploy notes are older notes (mid June) that I think I had not commited before.

**Comment by Zarquan** [comment]
> Note that the live deploy notes are older notes (mid June) that I think I had not commited before.

3 commits but only one file added.
Just to confirm, is that because you added and then deleted the notes from June 15th ?

**Comment by stvoutsin** [comment]
> > Note that the live deploy notes are older notes (mid June) that I think I had not commited before.
> 
> 3 commits but only one file added.
> Just to confirm, is that because you added and then deleted the notes from June 15th ?

I think there was a mistake there were I added some notes under the wrong directory, then deleted them. I've added the notes again in the right directory this time, and I've also added some notes on a test I ran yesterday on the recent tag.

**Comment by Zarquan** [comment]
> .. I added some notes under the wrong directory, then deleted them ..

OK, that explains it. I missed the directory path of the notes from the 15th.
All makes sense now :-)

**Review by Zarquan — APPROVED** [review]
:+1:

**Pull request merged**
