### PR TITLE
Added a github workflow, that runs yamllint on our deployment scripts

### PR DESCRIPTION
**Pull request by stvoutsin**

### CODE REVIEW

**Comment by Zarquan** [comment]
Can we rename the yamllint config file so that it is not hidden. `yamllint.yml` is fine, just remove the `'.'`.
General rule, we should not have any hidden files checked in to git.

**Comment by Zarquan** [comment]
I'd like to keep the extra spaces after colons. Disabling the [`max-spaces-after`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.colons) rule should do it.

    rules:
      colons:
        max-spaces-before: 0
        max-spaces-after: -1

**Comment by Zarquan** [comment]
If this works, should we promote it to the top level of the whole project ? Possibly leave as-is for this PR, test it out and then apply it to everything in a separate PR.

**Comment by stvoutsin** [comment]
> Can we rename the yamllint config file so that it is not hidden. `yamllint.yml` is fine, just remove the `'.'`. General rule, we should not have any hidden files checked in to git.

I've renamed the file in recent commit https://github.com/wfau/aglais/pull/615/commits/186941a63e1b96a6e57acef72702fe46f3030070
and 
https://github.com/wfau/aglais/pull/615/commits/186941a63e1b96a6e57acef72702fe46f3030070
(There was a typo in the first commit)

**Comment by stvoutsin** [comment]
> If this works, should we promote it to the top level of the whole project ? Possibly leave as-is for this PR, test it out and then apply it to everything in a separate PR.

We probbably should at some point, though when I ran it the first time it produced several errors, so there would be lots of cleaning up to do.

**Comment by stvoutsin** [comment]
> I'd like to keep the extra spaces after colons. Disabling the [`max-spaces-after`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.colons) rule should do it.
> 
> ```
> rules:
>   colons:
>     max-spaces-before: 0
>     max-spaces-after: -1
> ```

Ok this has been changed in commit: https://github.com/wfau/aglais/pull/615/commits/df8326bd25331ba736aa283d3b41557420a530b7

**Review by Zarquan — APPROVED** [review]
This is a good idea. We should look to do more of this.

**Pull request merged**
