### PR TITLE
20210227 zrq housekeeping

### PR DESCRIPTION
**Pull request by Zarquan**
Adding some things that I think we should support.

**Please don't merge this branch until everyone has reviewed and agreed to the changes**
I've asked for reviews from both of you because it would be good for all the contributors to see and agree to these changes.

We don't necessarily need these in our project, but if we add them here it may encourage other projects to do the same. I found out about the code of conduct and DCO because a search engine accident landed me on this project [CapeLeidokos/Aglais](https://github.com/CapeLeidokos/Aglais).

Added a code of conduct page:
* [CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)
* Based on the [Contributor Covenant](https://www.contributor-covenant.org/)

Added a [Developer Certificate of Origin](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin)
* [CONTRIBUTING](CONTRIBUTING.md)
* Based on the [Linux Foundation DCO](https://developercertificate.org/)

Added a Software Heritage badge
* Inspired by this talk [Software Source Code in Research and Open Science/ClipID:20063](https://www.fau.tv/clip/id/20063)

### CODE REVIEW

**Comment by Zarquan** [comment]
I added our work email addresses in the who to contact section of the code of conduct.
Please edit the text if you would prefer not to be in the list.

**Review by stvoutsin — COMMENTED** [review]
I'm happy to include these changes.

**Comment by NigelHambly** [comment]
Fine by me too.

**Comment by Zarquan** [comment]
@stvoutsin Could you approve the PR.

**Review by stvoutsin — APPROVED** [review]

**Pull request merged**
